# Generated by Django 3.2.5 on 2021-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Model',
            fields=[
                ('pno', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=200)),
                ('pprice', models.FloatField()),
                ('pphoto', models.FileField(upload_to='')),
            ],
        ),
    ]
